<a href="https://colab.research.google.com/github/zainab9271/Outfit-Compatibility-Prediction/blob/main/06_Gradio_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install Gradio

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!pip install gradio

In [ ]:
!unzip /content/drive/MyDrive/Outfit_Recommendation_Project/polyvore_outfits_images.zip

# Import Libraries

In [8]:
import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import shutil
import os

# Test Data

In [5]:
test_outfit_df = pd.read_csv('/content/drive/MyDrive/Outfit_Recommendation_Project/Normal_Outfits_Data/test4siamese.csv')
test_outfit_df

,tops,bottoms,shoes,outerwear,bags,compatibility
0,/content/content/polyvore_outfits/images/20684...,/content/content/polyvore_outfits/images/21200...,/content/content/polyvore_outfits/images/20998...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/drive/MyDrive/Outfit_Recommendation_P...,1
1,/content/content/polyvore_outfits/images/19402...,/content/content/polyvore_outfits/images/19103...,/content/content/polyvore_outfits/images/18830...,/content/content/polyvore_outfits/images/56965...,/content/content/polyvore_outfits/images/19739...,0
2,/content/content/polyvore_outfits/images/16719...,/content/content/polyvore_outfits/images/16421...,/content/content/polyvore_outfits/images/13551...,/content/content/polyvore_outfits/images/16225...,/content/content/polyvore_outfits/images/16835...,1
3,/content/content/polyvore_outfits/images/19584...,/content/content/polyvore_outfits/images/18452...,/content/content/polyvore_outfits/images/19741...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/18246...,1
4,/content/content/polyvore_outfits/images/21272...,/content/content/polyvore_outfits/images/11569...,/content/content/polyvore_outfits/images/21210...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/20903...,1
...,...,...,...,...,...,...
2910,/content/content/polyvore_outfits/images/82700...,/content/content/polyvore_outfits/images/11190...,/content/content/polyvore_outfits/images/12712...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/10648...,0
2911,/content/content/polyvore_outfits/images/15715...,/content/content/polyvore_outfits/images/20431...,/content/content/polyvore_outfits/images/16529...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/16202...,0
2912,/content/content/polyvore_outfits/images/12751...,/content/content/polyvore_outfits/images/13476...,/content/content/polyvore_outfits/images/12171...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/12232...,1
2913,/content/content/polyvore_outfits/images/20067...,/content/content/polyvore_outfits/images/18225...,/content/content/polyvore_outfits/images/18682...,/content/content/polyvore_outfits/images/15307...,/content/content/polyvore_outfits/images/21202...,0
2914,/content/content/polyvore_outfits/images/13360...,/content/content/polyvore_outfits/images/10735...,/content/content/polyvore_outfits/images/13274...,/content/drive/MyDrive/Outfit_Recommendation_P...,/content/content/polyvore_outfits/images/16624...,1

In [16]:
example_df = pd.DataFrame(columns=['tops', 'bottoms', 'shoes', 'outerwear', 'bags', 'compatibility'])

for i in range(10):
    samp = test_outfit_df.sample(1)
    samp.reset_index(drop=True, inplace=True)
    new_paths = []
    for item_path in samp.iloc[0,:-1]:
        new_paths.append(os.path.basename(shutil.copy(item_path, '/content')))
    new_paths.append(samp.iloc[0,-1])
    example_df = example_df.append(dict(zip(list(example_df.columns), new_paths)), ignore_index=True)
    


example_df

,tops,bottoms,shoes,outerwear,bags,compatibility
0,201893919.jpg,201893808.jpg,177546185.jpg,blank_image.jpg,188111069.jpg,1
1,105583368.jpg,151173851.jpg,150909412.jpg,153603791.jpg,156957101.jpg,1
2,176167550.jpg,171356827.jpg,215285740.jpg,blank_image.jpg,194850161.jpg,0
3,209900268.jpg,201306642.jpg,197264977.jpg,blank_image.jpg,200509502.jpg,0
4,66998661.jpg,49335536.jpg,66571560.jpg,64177514.jpg,68624796.jpg,1
5,183376788.jpg,191319256.jpg,144990994.jpg,blank_image.jpg,blank_image.jpg,0
6,215512954.jpg,214346897.jpg,214161953.jpg,blank_image.jpg,blank_image.jpg,1
7,144123209.jpg,142678059.jpg,172611288.jpg,146257930.jpg,144846157.jpg,1
8,129287946.jpg,132845929.jpg,134522969.jpg,128117518.jpg,134163766.jpg,1
9,149578911.jpg,151094417.jpg,149767690.jpg,139848225.jpg,blank_image.jpg,1

In [17]:
example_log = example_df.iloc[:,:-1]
example_log

,tops,bottoms,shoes,outerwear,bags
0,201893919.jpg,201893808.jpg,177546185.jpg,blank_image.jpg,188111069.jpg
1,105583368.jpg,151173851.jpg,150909412.jpg,153603791.jpg,156957101.jpg
2,176167550.jpg,171356827.jpg,215285740.jpg,blank_image.jpg,194850161.jpg
3,209900268.jpg,201306642.jpg,197264977.jpg,blank_image.jpg,200509502.jpg
4,66998661.jpg,49335536.jpg,66571560.jpg,64177514.jpg,68624796.jpg
5,183376788.jpg,191319256.jpg,144990994.jpg,blank_image.jpg,blank_image.jpg
6,215512954.jpg,214346897.jpg,214161953.jpg,blank_image.jpg,blank_image.jpg
7,144123209.jpg,142678059.jpg,172611288.jpg,146257930.jpg,144846157.jpg
8,129287946.jpg,132845929.jpg,134522969.jpg,128117518.jpg,134163766.jpg
9,149578911.jpg,151094417.jpg,149767690.jpg,139848225.jpg,blank_image.jpg

In [11]:
model = tf.keras.models.load_model('/content/drive/MyDrive/Outfit_Recommendation_Project/best_model_4_normal_outfits')
model.summary()

Model: "siamese_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 densenet121 (Functional)    (None, 7, 7, 1024)        7037504

 dense (Dense)               multiple                  2621440

 batch_normalization (BatchN  multiple                 2048
 ormalization)

 dense_1 (Dense)             multiple                  65536

 batch_normalization_1 (Batc  multiple                 512
 hNormalization)

 dense_2 (Dense)             multiple                  129

=================================================================
Total params: 9,727,169
Trainable params: 2,688,385
Non-trainable params: 7,038,784
_________________________________________________________________

# Gradio for Our Model

In [12]:
def predict_outfit_compatibility(image1, image2, image3, image4, image5):
    
    image1 = image1/255.0
    image1 = tf.expand_dims(image1, axis=0)

    image2 = image2/255.0
    image2 = tf.expand_dims(image2, axis=0)

    image3 = image3/255.0
    image3 = tf.expand_dims(image3, axis=0)

    if image4 is None:
        image4 = plt.imread('/content/drive/MyDrive/Outfit_Recommendation_Project/blank_image.jpg').astype('float32')
    else:
        image4 = image4/255.0
    image4 = tf.expand_dims(image4, axis=0)

    if image5 is None:
        image5 = plt.imread('/content/drive/MyDrive/Outfit_Recommendation_Project/blank_image.jpg').astype('float32')
    else:
        image5 = image5/255.0
    image5 = tf.expand_dims(image5, axis=0)

    prediction = model.predict((image1, image2, image3, image4, image5))
    return {'Compatible':float(prediction[0][0]), 'Incompatible':float(1 - prediction[0][0])}

In [18]:
gr.Interface(
    fn=predict_outfit_compatibility, 
    inputs=[gr.inputs.Image(shape=(224,224), label='Top'),
            gr.inputs.Image(shape=(224,224), label='Bottom'),
            gr.inputs.Image(shape=(224,224), label='Shoes'),
            gr.inputs.Image(shape=(224,224), label='Outerwear', optional=True),
            gr.inputs.Image(shape=(224,224), label='Bags', optional=True)
            ],
    outputs = gr.outputs.Label(num_top_classes=2),
    title='Outfit Compatibility Inspector',
    description='Pick up at least 3 items and check if your selected items are compatible to be considered as an outfit.',
    theme='peach',
    examples=example_log.to_numpy().tolist()
    ).launch()

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://56576.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<fastapi.applications.FastAPI at 0x7fec13859610>,
 'http://127.0.0.1:7861/',
 'https://56576.gradio.app')